### ISSUE TITLE
Class 'conquer\codemirror\ArrayHelper' not found

### ISSUE THREAD

**Issue by dbsparkle** [borodulin/yii2-codemirror#1]
"vendor/conquer/codemirror/CodemirrorAsset.php"  line 436:

Written:
`self::$_assets=ArrayHelper::merge(self::$_assets, array_flip($assets));`

but `\yii\helpers\ArrayHelper` hasn`t been imported

should be `self::$_assets=\yii\helpers\ArrayHelper::merge(self::$_assets, array_flip($assets));`

**Comment by borodulin** [comment]
Thank you!
https://github.com/borodulin/yii2-codemirror/commit/5cf880dd6b61fc3a255cfe937afcbd46147ae896
