### ISSUE TITLE
javascript inline code has to be fixed

### ISSUE THREAD

**Issue by iz65535** [borodulin/yii2-codemirror#12]
Hello
i've tried to use this in my form, with inline javascript, generated by Yii (client side active form validators). 
So yii has to generate "total" inline javascript from the pieces. Since codemirror code doesn't contain ";" at the end, this breaks the rest of inline code.
How to fix that (CodeMirrorWidget.php:64):

remove this line        $js = "CodeMirror.fromTextArea(document.getElementById('$id'), $settings)";
add this line       $js = "CodeMirror.fromTextArea(document.getElementById('$id'), $settings);";

This also can be fixed in user view: 
$this->registerJs(';'); // right after you've used the widget, so it will just append the delimiter;

**Comment by borodulin** [comment]
Hi! Can you make a pull request?

**Comment by iz65535** [comment]
https://github.com/borodulin/yii2-codemirror/pull/13
