### ISSUE TITLE
Strange behaviour under Yii2 tabs

### ISSUE THREAD

**Issue by ebtc** [borodulin/yii2-codemirror#4]
When placing the codemirror widget (as part of a model form) under tabs content the behaviour is unexpected. The editor loads on focus of the textarea and no content can be selected. I did not see any js errors in the console.

There must be a conflict somewhere. Here is a snippet of the usage:

```
echo Tabs::widget([
    'items' => [
        [
            'label' => 'General',
            'content' => $generalSection,
            'active' => true
        ],
        [
            'label' => 'Style Setup',
            'content' => '
            <fieldset>
                <legend>Style Setup</legend>
                <div>'.
                $form->field($model, 'styles')->widget(
                    CodemirrorWidget::className(),
                    [
                        'preset'=>'php',
                        'options'=>['rows' => 30],
                    ]
                ).
                '</div>
            </fieldset>
            '
        ],

.... 
```

And ideas?

**Comment by borodulin** [comment]
Hi!
I tried to reproduce the error, but I have everything working perfectly.
I used yii\jui\Tabs and yii\bootstrap\Tabs - every tab works fine with the Codemirror.
In any case, it seems to specific problem in your JS libraries. May be there are some conflicts, overlaps of the event handlers or something else.Try to exclude the scripts one by one, to determine the cause
