### ISSUE TITLE
Set settings for CodemirrorWidget

### ISSUE THREAD

**Issue by RuslanKhudenko** [borodulin/yii2-codemirror#6]
Привет.
Пытаюсь установить ключ "extraKeys" в настройках виджету, ничего не выходит.
Делаю как строкой:
"extraKeys" =>  '{"F2": function(cm) {cm.setOption("fullScreen", !cm.getOption("fullScreen"));}}' - не получается.

Делаю как массивом
"extraKeys" => [
    "F2" => 'function(cm) {cm.setOption("fullScreen", !cm.getOption("fullScreen"));}'
  ] - тоже не получается.

(Нужные Assets для этого подключил)
Не могли бы вы мне помочь с синтаксисом ? спасибо.

**Comment by borodulin** [comment]
можно вот так: "extraKeys" => ['F2' =>  'js:function(cm) {cm.setOption("fullScreen", !cm.getOption("fullScreen"));}'],
"js:blabla" - это специальная фишка из conquer\helpers\Json, заменяет конструкцию (new Expression('blabla')). В первом Yii такое поведение поддерживалось на уровне фреймворка, в новом - только через выражение Expression, либо вот, допиливать.
