### ISSUE TITLE
install issue using composer

### ISSUE THREAD

**Issue by manojkumar1412** [borodulin/yii2-codemirror#7]
I was trying to use this extension, but i was getting below error.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - conquer/codemirror 2.0 requires bower-asset/codemirror \* -> no matching package found.
    - conquer/codemirror 1.2 requires bower-asset/codemirror \* -> no matching package found.
    - conquer/codemirror 1.1 requires bower-asset/codemirror \* -> no matching package found.
    - conquer/codemirror 1.0 requires bower-asset/codemirror \* -> no matching package found.
    - Installation request for conquer/codemirror \* -> satisfiable by conquer/codemirror[1.0, 1.1, 1.2, 2.0].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Please help me out

**Comment by borodulin** [comment]
It seems you have not finished installing yii.
http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-yii
a key line for you:

> composer global require "fxp/composer-asset-plugin:^1.2.0"
